PREFIX aas: <https://admin-shell.io/aas/3/0/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tto: <https://w3id.org/pmd/tto/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

PREFIX ns1: <https://admin-shell.io/aas/3/0/Property/>
PREFIX ns2: <https://admin-shell.io/aas/3/0/Key/>
PREFIX ns3: <https://admin-shell.io/aas/3/0/Reference/>
PREFIX ns5: <https://admin-shell.io/aas/3/0/HasSemantics/>

PREFIX ex: <http://www.example.org/#>
PREFIX material: <https://w3id.org/pmd/co/PMD_0000000>
PREFIX chemical_composition: <https://w3id.org/pmd/co/PMD_0000551>
PREFIX chemical_composition_specification: <https://w3id.org/pmd/co/PMD_0025002>
PREFIX fraction_value_specification: <https://w3id.org/pmd/co/PMD_0025997>
PREFIX mass_proportion: <https://w3id.org/pmd/co/PMD_0020102>
PREFIX portion_of_nickel: <https://w3id.org/pmd/co/PMD_0020051>
PREFIX portion_of_carbon: <https://w3id.org/pmd/co/PMD_0020030>
PREFIX portion_of_chromium: <https://w3id.org/pmd/co/PMD_0020029>
PREFIX portion_of_molybdenum: <https://w3id.org/pmd/co/PMD_0020034>
PREFIX portion_of_manganese: <https://w3id.org/pmd/co/PMD_0020078>
PREFIX portion_of_silicon: <https://w3id.org/pmd/co/PMD_0020050>
PREFIX portion_of_phosphorus: <https://w3id.org/pmd/co/PMD_0020047>
PREFIX portion_of_sulfur: <https://w3id.org/pmd/co/PMD_0020059>
PREFIX portion_of_nitrogen: <https://w3id.org/pmd/co/PMD_0020038>

PREFIX quality_of: <http://purl.obolibrary.org/obo/RO_0000080>
PREFIX has_member: <http://purl.obolibrary.org/obo/RO_0002351>
PREFIX is_subject_of: <https://w3id.org/pmd/co/PMD_0000004>
PREFIX specified_by_value: <https://w3id.org/pmd/co/PMD_0000077>
PREFIX relational_quality_of: <https://w3id.org/pmd/co/PMD_0025999>
PREFIX has_specified_numeric_value: <http://purl.obolibrary.org/obo/OBI_0001937>
PREFIX has_measurement_unit_label: <http://purl.obolibrary.org/obo/IAO_0000039>
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050>

PREFIX scalar_value_specification: <http://purl.obolibrary.org/obo/OBI_0001931>
PREFIX specifies_value_of: <http://purl.obolibrary.org/obo/OBI_0001927>
PREFIX mass_percentage: <http://purl.obolibrary.org/obo/UO_0000163>

CONSTRUCT {

  ex:PLACEHOLDER_material a material: .

  # ================ Material properties ===============
  ex:PLACEHOLDER_tensile_strength a tto:TTO_0000053 ;
    quality_of: ex:PLACEHOLDER_material . 

  ex:PLACEHOLDER_tensile_strength_value a scalar_value_specification: ;
    has_specified_numeric_value: ?tensileStrengthValueFinal ;
    has_measurement_unit_label: qudt:MegaPA ; 
    specifies_value_of: ex:PLACEHOLDER_tensile_strength .

  ex:PLACEHOLDER_yield_strength a tto:TTO_0000009 ;
    quality_of: ex:PLACEHOLDER_material . 

  ex:PLACEHOLDER_yield_strength_value a scalar_value_specification: ;
    has_specified_numeric_value: ?yieldStrengthValueFinal ;
    has_measurement_unit_label: qudt:MegaPA ; 
    specifies_value_of: ex:PLACEHOLDER_yield_strength .

  ex:PLACEHOLDER_elongation_after_fracture a tto:TTO_0000033 ;
    quality_of: ex:PLACEHOLDER_material . 

  ex:PLACEHOLDER_elongation_after_fracture_value a scalar_value_specification: ;
    has_specified_numeric_value: ?elongationAfterFractureValueFinal ;
    has_measurement_unit_label: qudt:PERCENT ; 
    specifies_value_of: ex:PLACEHOLDER_elongation_after_fracture .

  # ========= Chemical composition =========
  # Chemical elements and mass proportions
  ex:PLACEHOLDER_some_carbon a portion_of_carbon: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_nickel a portion_of_nickel: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_chromium a portion_of_chromium: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_silicon a portion_of_silicon: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_manganese a portion_of_manganese: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_phosphorus a portion_of_phosphorus: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_sulfur a portion_of_sulfur: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_molybdenum a portion_of_molybdenum: ; part_of: ex:PLACEHOLDER_material .
  ex:PLACEHOLDER_some_nitrogen a portion_of_nitrogen: ; part_of: ex:PLACEHOLDER_material .

  ex:PLACEHOLDER_chem_comp a chemical_composition: ;
      quality_of: ex:PLACEHOLDER_material ;
      is_subject_of: ex:PLACEHOLDER_chem_comp_spec .

  ex:PLACEHOLDER_chem_comp_spec a chemical_composition_specification: ;
      has_member: ex:PLACEHOLDER_fraction_carbon ;
      has_member: ex:PLACEHOLDER_fraction_nickel ;
      has_member: ex:PLACEHOLDER_fraction_chromium ;
      has_member: ex:PLACEHOLDER_fraction_silicon ;
      has_member: ex:PLACEHOLDER_fraction_manganese ;
      has_member: ex:PLACEHOLDER_fraction_phosphorus ;
      has_member: ex:PLACEHOLDER_fraction_sulfur ;
      has_member: ex:PLACEHOLDER_fraction_molybdenum ;
      has_member: ex:PLACEHOLDER_fraction_nitrogen .

  # Mass proportions
  ex:PLACEHOLDER_mass_proportion_carbon a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_carbon ;
      specified_by_value: ex:PLACEHOLDER_fraction_carbon .
  ex:PLACEHOLDER_mass_proportion_nickel a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_nickel ;
      specified_by_value: ex:PLACEHOLDER_fraction_nickel .
  ex:PLACEHOLDER_mass_proportion_chromium a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_chromium ;
      specified_by_value: ex:PLACEHOLDER_fraction_chromium .
  ex:PLACEHOLDER_mass_proportion_silicon a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_silicon ;
      specified_by_value: ex:PLACEHOLDER_fraction_silicon .
  ex:PLACEHOLDER_mass_proportion_manganese a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_manganese ;
      specified_by_value: ex:PLACEHOLDER_fraction_manganese .
  ex:PLACEHOLDER_mass_proportion_phosphorus a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_phosphorus ;
      specified_by_value: ex:PLACEHOLDER_fraction_phosphorus .
  ex:PLACEHOLDER_mass_proportion_sulfur a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_sulfur ;
      specified_by_value: ex:PLACEHOLDER_fraction_sulfur .
  ex:PLACEHOLDER_mass_proportion_molybdenum a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_molybdenum ;
      specified_by_value: ex:PLACEHOLDER_fraction_molybdenum .
  ex:PLACEHOLDER_mass_proportion_nitrogen a mass_proportion: ;
      relational_quality_of: ex:PLACEHOLDER_some_nitrogen ;
      specified_by_value: ex:PLACEHOLDER_fraction_nitrogen .

  # Fraction specifications
  ex:PLACEHOLDER_fraction_carbon a fraction_value_specification: ;
      has_specified_numeric_value: ?carbonValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_nickel a fraction_value_specification: ;
      has_specified_numeric_value: ?nickelValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_chromium a fraction_value_specification: ;
      has_specified_numeric_value: ?chromiumValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_silicon a fraction_value_specification: ;
      has_specified_numeric_value: ?siliconValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_manganese a fraction_value_specification: ;
      has_specified_numeric_value: ?manganeseValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_phosphorus a fraction_value_specification: ;
      has_specified_numeric_value: ?phosphorusValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_sulfur a fraction_value_specification: ;
      has_specified_numeric_value: ?sulfurValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_molybdenum a fraction_value_specification: ;
      has_specified_numeric_value: ?molybdenumValueFinal ;
      has_measurement_unit_label: mass_percentage: .
  ex:PLACEHOLDER_fraction_nitrogen a fraction_value_specification: ;
      has_specified_numeric_value: ?nitrogenValueFinal ;
      has_measurement_unit_label: mass_percentage: .

}
WHERE {

  # Tensile strength
  OPTIONAL {
    ?tensileStrengthProp a aas:Property ;
        ns1:value ?tensileStrengthValue ;
        ns5:supplementalSemanticIds ?tensileStrengthSS .
    ?tensileStrengthSS ns3:keys ?tensileStrengthKey .
    ?tensileStrengthKey ns2:value "https://w3id.org/pmd/tto/TTO_0000053" .

  } 
  BIND(COALESCE(?tensileStrengthValue, "N/A") AS ?tensileStrengthValueFinal)

  # Yield strength
  OPTIONAL {
    ?yieldStrengthProp a aas:Property ;
        ns1:value ?yieldStrengthValue ;
        ns5:supplementalSemanticIds ?yieldStrengthSS .
    ?yieldStrengthSS ns3:keys ?yieldStrengthKey .
    ?yieldStrengthKey ns2:value "https://w3id.org/pmd/tto/TTO_0000009" .

  }
  BIND(COALESCE(?yieldStrengthValue, "N/A") AS ?yieldStrengthValueFinal)

  # Elongation after fracture
  OPTIONAL {
    ?elongationProp a aas:Property ;
        ns1:value ?elongationAfterFractureValue ;
        ns5:supplementalSemanticIds ?elongationSS .
    ?elongationSS ns3:keys ?elongationKey .
    ?elongationKey ns2:value "https://w3id.org/pmd/tto/TTO_0000033" .
  }
  BIND(COALESCE(?elongationAfterFractureValue, "N/A") AS ?elongationAfterFractureValueFinal)

  # Optional binding for all elements with default 0
  OPTIONAL {
    ?carbonProp a aas:Property ; ns1:value ?carbonValue ; ns5:supplementalSemanticIds ?carbonSS .
    ?carbonSS ns3:keys ?carbonKey . ?carbonKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_27594" .
  }
  BIND(COALESCE(?carbonValue, "N/A") AS ?carbonValueFinal)

  OPTIONAL {
    ?nickelProp a aas:Property ; ns1:value ?nickelValue ; ns5:supplementalSemanticIds ?nickelSS .
    ?nickelSS ns3:keys ?nickelKey . ?nickelKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_28112" .
  }
  BIND(COALESCE(?nickelValue, "N/A") AS ?nickelValueFinal)

  OPTIONAL {
    ?chromiumProp a aas:Property ; ns1:value ?chromiumValue ; ns5:supplementalSemanticIds ?chromiumSS .
    ?chromiumSS ns3:keys ?chromiumKey . ?chromiumKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_28073" .
  }
  BIND(COALESCE(?chromiumValue, "N/A") AS ?chromiumValueFinal)

  OPTIONAL {
    ?siliconProp a aas:Property ; ns1:value ?siliconValue ; ns5:supplementalSemanticIds ?siliconSS .
    ?siliconSS ns3:keys ?siliconKey . ?siliconKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_27573" .
  }
  BIND(COALESCE(?siliconValue, "N/A") AS ?siliconValueFinal)

  OPTIONAL {
    ?manganeseProp a aas:Property ; ns1:value ?manganeseValue ; ns5:supplementalSemanticIds ?manganeseSS .
    ?manganeseSS ns3:keys ?manganeseKey . ?manganeseKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_18291" .
  }
  BIND(COALESCE(?manganeseValue, "N/A") AS ?manganeseValueFinal)

  OPTIONAL {
    ?phosphorusProp a aas:Property ; ns1:value ?phosphorusValue ; ns5:supplementalSemanticIds ?phosphorusSS .
    ?phosphorusSS ns3:keys ?phosphorusKey . ?phosphorusKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_28659" .
  }
  BIND(COALESCE(?phosphorusValue, "N/A") AS ?phosphorusValueFinal)

  OPTIONAL {
    ?sulfurProp a aas:Property ; ns1:value ?sulfurValue ; ns5:supplementalSemanticIds ?sulfurSS .
    ?sulfurSS ns3:keys ?sulfurKey . ?sulfurKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_26833" .
  }
  BIND(COALESCE(?sulfurValue, "N/A") AS ?sulfurValueFinal)

  OPTIONAL {
    ?molybdenumProp a aas:Property ; ns1:value ?molybdenumValue ; ns5:supplementalSemanticIds ?molybdenumSS .
    ?molybdenumSS ns3:keys ?molybdenumKey . ?molybdenumKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_28685" .
  }
  BIND(COALESCE(?molybdenumValue, "N/A") AS ?molybdenumValueFinal)

  OPTIONAL {
    ?nitrogenProp a aas:Property ; ns1:value ?nitrogenValue ; ns5:supplementalSemanticIds ?nitrogenSS .
    ?nitrogenSS ns3:keys ?nitrogenKey . ?nitrogenKey ns2:value "http://purl.obolibrary.org/obo/CHEBI_25555" .
  }
  BIND(COALESCE(?nitrogenValue, "N/A") AS ?nitrogenValueFinal)

}
